import { useEffect } from 'react'

type TermsOfServiceModalProps = {
  isOpen: boolean
  onClose: () => void
}

const sections = [
  {
    title: '1. What this is',
    paragraphs: [
      'firstinterview.ai is a free AI-powered practice interview tool operated by Remgu LLC. You can upload your CV, complete a voice-based interview, and receive a scorecard with feedback.',
      'The service is intended to help you practice your interviews and improve your performance. It is also used by us to improve the quality and accuracy of the service.',
    ],
  },
  {
    title: '2. Eligibility',
    paragraphs: [
      'You must be at least 18 years old to use this service. By using the service, you represent that the information and materials you provide are accurate and that you have the right to provide them.',
    ],
  },
  {
    title: '3. How it works',
    paragraphs: [
      'You may provide your first name, last name, email address, LinkedIn profile URL, GitHub profile URL, CV, and spoken answers to interview questions. Our AI uses your CV to generate tailored questions, transcribe your answers, and produce a scorecard with feedback.',
      'Your results may be shown on screen and emailed to you. The scorecard is intended as practice feedback only and should not be treated as a definitive statement of your skills, qualifications, or likely hiring outcome.',
    ],
  },
  {
    title: '4. Recording',
    paragraphs: [
      'The interview includes video and audio recording of your responses. Both video and audio recordings are used to generate your scorecard and operate the service. By starting the interview, you acknowledge and consent to video and audio recording, transcription, and related processing as described in these Terms and the Privacy Policy.',
      'Video and audio recordings are deleted from our systems within 72 hours of your interview. Transcripts, CVs, and scorecards are retained longer as described in the Privacy Policy.',
      'If you do not want to be recorded, do not use the interview feature.',
    ],
  },
  {
    title: '5. Use of your data',
    paragraphs: [
      'Your CV is used to tailor interview questions to your background. Your LinkedIn and GitHub profiles are used to verify your professional background. Your video and audio recordings, transcript, and scorecard are used to provide you with feedback and to improve the service.',
      'Your email is used to send you your scorecard and service-related communications. We do not sell your personal data to advertisers or third-party data brokers.',
      'Using firstinterview.ai does not enroll you in the Remgu talent network and does not authorize us to share your profile with hiring companies by default. If we believe you may be a fit for an opportunity, we may contact you separately to ask whether you would like to opt in to the Remgu talent network. We will not share your profile, CV, scorecard, transcript, or contact information with hiring companies unless you separately choose to opt in.',
    ],
  },
  {
    title: '6. AI-generated content',
    paragraphs: [
      'Scores and feedback are generated by AI. They are intended as guidance only and are not a guarantee of job performance, hiring outcomes, or suitability for any role.',
      'AI-generated outputs may be incomplete or inaccurate and should not be treated as a definitive assessment of your abilities.',
    ],
  },
  {
    title: '7. Acceptable use',
    paragraphs: [
      'Do not upload fraudulent, misleading, infringing, or unauthorized materials. Do not misuse the service, attempt to reverse-engineer it, interfere with its operation, or use it in a harmful or unlawful way.',
      'We reserve the right to suspend or terminate access if we reasonably believe these Terms have been violated.',
    ],
  },
  {
    title: '8. Accessibility and accommodations',
    paragraphs: [
      'If you need an accommodation or alternative format due to disability, speech, language, hearing, audio, or connectivity limitations, contact support@firstinterview.ai. Where reasonably possible, we will try to provide an alternative process or support.',
    ],
  },
  {
    title: '9. Data deletion',
    paragraphs: [
      'You may request deletion of your personal data at any time by emailing support@firstinterview.ai. Upon request, we will delete your scorecard, transcript, CV, contact information, and any remaining personal data from our systems within 30 days, subject to any legal, security, fraud-prevention, or recordkeeping obligations that require limited retention.',
      "If you later separately opt in to the Remgu talent network and your information is shared with a hiring company, data already shared before your deletion request cannot be retroactively deleted from that company's systems by us.",
    ],
  },
  {
    title: '10. Dispute resolution',
    paragraphs: [
      'Before initiating any legal proceeding, you agree to contact support@firstinterview.ai and provide a written description of the dispute. Both parties agree to attempt to resolve the matter informally for at least 60 days before pursuing any formal action.',
    ],
  },
  {
    title: '11. Class action waiver',
    paragraphs: [
      'You agree that any dispute arising from or related to your use of firstinterview.ai will be resolved on an individual basis only. You waive any right to bring or participate in any class action, collective action, or representative proceeding against Remgu LLC.',
    ],
  },
  {
    title: '12. Limitation of liability',
    paragraphs: [
      'firstinterview.ai is provided "as is" and "as available" without warranties of any kind, to the maximum extent permitted by law. We do not guarantee uninterrupted availability, error-free operation, or the accuracy of AI-generated content.',
      'To the maximum extent permitted by law, Remgu LLC and firstinterview.ai are not liable for indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the service. Nothing in these Terms limits liability that cannot be limited under applicable law.',
    ],
  },
  {
    title: '13. Changes',
    paragraphs: [
      'We may update these Terms from time to time. Continued use of the service after updated Terms become effective constitutes acceptance of the updated Terms.',
    ],
  },
  {
    title: '14. Contact',
    paragraphs: ['If you have questions about these Terms, contact'],
  },
] as const

export function TermsOfServiceModal({ isOpen, onClose }: TermsOfServiceModalProps) {
  useEffect(() => {
    if (!isOpen) {
      return
    }

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onClose()
      }
    }

    document.body.style.overflow = 'hidden'
    window.addEventListener('keydown', handleKeyDown)

    return () => {
      document.body.style.overflow = ''
      window.removeEventListener('keydown', handleKeyDown)
    }
  }, [isOpen, onClose])

  if (!isOpen) {
    return null
  }

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6"
      role="dialog"
      aria-modal="true"
      aria-labelledby="terms-of-service-title"
    >
      <button
        type="button"
        className="absolute inset-0 bg-[#0f172a]/55 backdrop-blur-[1px]"
        aria-label="Close Terms of Service"
        onClick={onClose}
      />

      <div className="relative w-full max-w-4xl overflow-hidden rounded-2xl bg-white shadow-[0px_25px_60px_-12px_rgba(2,6,23,0.35)]">
        <div className="flex items-start justify-between gap-4 border-b border-fi-border px-5 py-4 sm:px-7 sm:py-5">
          <div>
            <h2 id="terms-of-service-title" className="font-display text-2xl font-bold text-fi-ink sm:text-[2rem]">
              Terms of Service
            </h2>
            <p className="mt-1 text-sm text-fi-muted">Last updated: April 2, 2026</p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-md text-fi-muted transition-colors hover:bg-[#f3f4f6] hover:text-fi-ink"
            aria-label="Close Terms of Service"
          >
            <svg viewBox="0 0 16 16" className="h-4 w-4" fill="none" aria-hidden>
              <path d="M3 3l10 10M13 3L3 13" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
            </svg>
          </button>
        </div>

        <div className="max-h-[78vh] overflow-y-auto px-5 py-5 sm:px-7 sm:py-6">
          <div className="space-y-6 text-[15px] leading-relaxed text-[#374151] sm:text-base">
            {sections.map((section) => (
              <section key={section.title} className="space-y-2.5">
                <h3 className="font-display text-[1.05rem] font-semibold text-fi-ink sm:text-[1.2rem]">
                  {section.title}
                </h3>
                {section.paragraphs.map((paragraph) => (
                  <p key={paragraph}>
                    {section.title === '14. Contact' ? (
                      <>
                        {paragraph}{' '}
                        <a
                          href="mailto:support@firstinterview.ai"
                          className="text-fi-blue underline underline-offset-2 transition-opacity hover:opacity-85"
                        >
                          support@firstinterview.ai
                        </a>
                        .
                      </>
                    ) : (
                      paragraph
                    )}
                  </p>
                ))}
              </section>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
